apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: ${DOCKERHUB_USERNAME}/my-java-app:${GITHUB_SHA}
        ports:
        - containerPort: 8080
        

